# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.badals.shop: INFO
    io.github.jhipster: INFO
    io.netty.util: ERROR

management:
  metrics:
    export:
      prometheus:
        enabled: false

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://badal-website-fra.cuv8f0sngmtx.eu-central-1.rds.amazonaws.com/shop?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: shop-api
    password: 4158yORAQ64ipEXobeFO385O6olo7oKp~
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximum-pool-size: 50
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  data:
    jest:
      uri: https://d68af11bb6364c90b56a8215597289b1.eu-central-1.aws.cloud.es.io:9243
      username: elastic
      password: U4s3g1aeygWkZbbeK8urU7KM
  # see https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-nosql.html#boot-features-connecting-to-elasticsearch-jest
  elasticsearch:
    rest:
      uris: https://d68af11bb6364c90b56a8215597289b1.eu-central-1.aws.cloud.es.io:9243
      username: elastic
      password: U4s3g1aeygWkZbbeK8urU7KM
  # Replace by 'prod, faker' to add the faker context and have sample data loaded in production
  liquibase:
    contexts: prod
  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: ali@badals.com
    password: ***REMOVED***
  thymeleaf:
    cache: true
  redis:
    host: redis-15021.c135.eu-central-1-1.ec2.cloud.redislabs.com
    port: 15021
    password: Vl0wz1HVcaskE4Z9b3D8MIbBQefLOXkT

# ===================================================================
# To enable TLS in production, generate a certificate using:
# keytool -genkey -alias shop -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 443
#    ssl:
#        key-store: classpath:config/tls/keystore.p12
#        key-store-password: password
#        key-store-type: PKCS12
#        key-alias: shop
#        # The ciphers suite enforce the security by deactivating some old and deprecated SSL cipher, this list was tested against SSL Labs (https://www.ssllabs.com/ssltest/)
#        ciphers: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 ,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA,TLS_RSA_WITH_CAMELLIA_128_CBC_SHA
# ===================================================================
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  http:
    cache: # Used by the CachingHttpHeadersFilter
      timeToLiveInDays: 1461
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 600 # By default objects stay 1 hour in the cache
      max-entries: 1000 # Number of objects in each cache entry
  cors:
    allowed-origins: 'https://www.badals.com,https://badals.com,https://partner.badals.com,https://face-admin.herokuapp.com,https://trust-admin001-212.badals.com'
    allowed-methods: 'GET,PUT,POST,DELETE,OPTIONS'
    allowed-headers: 'Authorization,Content-Type,x-requested-with,origin'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        # As this is the PRODUCTION configuration, you MUST change the default key, and store it securely:
        # - In the JHipster Registry (which includes a Spring Cloud Config server)
        # - In a separate `application-prod.yml` file, in the same folder as your executable JAR file
        # - In the `JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET` environment variable
        base64-secret: NzQwMjdjZTQyZTJkMWJlNTEzOTU4ZDFhZWU1OGNkZmI5YTg5ZGEzNjkzZjU0M2U5OWY3MWI2NGJjNTVkNzM5ZTBlYWYwMWZhZmUwMmE5MDNlZjJiN2E2MWNlMDg0YTU0MjRjNTkwOTVmZWE3NGI2NTRkZjE2NzllM2ZjOTMyYjM=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    from: sales@badals.com
    base-url: https://www.badals.com # Modify according to your server's URL
  metrics:
    logs: # Reports metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
# application:
translate:
  key: AIzaSyBL1StO62qTC5QTo3Ds8wKrIfwO6vMNMMY

pas:
  key: ***REMOVED***
  secret: ***REMOVED***
  us:
    tag: 4242020-20
    host: webservices.amazon.com
    region: us-east-1
  uk:
    tag: exercisebikeu-21
    host: webservices.amazon.co.uk
    region: eu-west-1

aws:
  s3bucket: face-content

mws:
  key: ***REMOVED***
  secret: ***REMOVED***
  merchantid: ***REMOVED***
  marketplaceid: ***REMOVED***

badals:
  checkout-app: https://checkout.badals.com/checkout/start
  cdnUrl: https://cdn.badals.com
  s3bucket: face-content
  sk: sk_56109822-a7d8-41f7-ae5d-c332b6bcd995

ebay:
  app-id: v^1.1#i^1#r^0#f^0#p^1#I^3#t^H4sIAAAAAAAAAOVYf2wTVRxfu24EoRCUiU7EcghR9K53115/XGi1o0yW/erWbrJNxXd378ax691x75W1kpi5P1BjNGrgD8Qf/BJNUCMh6EDU8AcRJSQGTVCJBokhGEFCQDAxinddGd0kgLQxS2ybNO/7vu/7Pp/P+37fe3f0QPXE+asXr77gdkxwbhigB5wOBzOJnlhddd+USmdtVQVd5ODYMHD3gGuw8sQCBNKqwbdDZOgagp5sWtUQnzdGiIyp8TpACuI1kIaIxyKfjDU38SxF84apY13UVcLTEI8QgRDk/BwI+oSwxIrBgGXVLsVM6RGCYYOSyIpyOAzCIMAwVj9CGdigIQw0HCFYmmVIhrZ+KYbmfTTPcRQTCHQTnk5oIkXXLBeKJqJ5uHx+rFmE9epQAULQxFYQItoQq0+2xhrii1pSC7xFsaIFHZIY4Awa3VqoS9DTCdQMvPo0KO/NJzOiCBEivNHhGUYH5WOXwNwA/LzUYZllYIAOi4BjABP0lUXKet1MA3x1HLZFkUg578pDDSs4dy1FLTWE5VDEhVaLFaIh7rH/2jJAVWQFmhFiUV2sK5ZIENE6IAE1ZQKSk/ws6eckSAp0WCC5UECWGb8AuaBcmGQ4UkHiMbMs1DVJsQVDnhYd10ELMRyrC1uki+XUqrWaMRnbaIr92BH9mG57QYdXMIOXafaawrQlgiffvLb6I6MxNhUhg+FIhLEdeXkiBDAMRSLGdubzsJA6WRQhlmFs8F5vf38/1e+jdLPXy9I0413S3JQUl8E0IAq+dq1nkXLtAaSSpyJCayRSeJwzLCxZK08tAFovEQ2HaCZYkH00quhY6z8MRZS9o4uhXMURFIIwJISCMsMKMheG5SiOaCE/vTYOKIAcmQZmH8SGCkRIilaaZdLQVCTex8msLyRDUgqEZdIflmVS4KQAycgQ0hAKghgO/V9q5HqzPAlFE+KypXlZUjyXkeK9YrAlF2uJL86yoY4VQGzK+psTi1BHggUhASXrkv7GvodiDZHrrYQrkl+oKpYyKWv+sgpg13rJIizWEYZSSfSSom7AhK4qYm58LbDPlBLAxLkkVFXLUBLJmGE0lG+bLgu9f7FF3Bjn8h5N//2xdEVSyM7W8UXKHo+sAMBQKPvgoUQ97dWBdeGwTUttxHatw5J4K9ZddVyxtkgOs1Wk4UsmladMoZUiZUKkZ0zrfk212veulN4HNesow6auqtDsZEou5XQ6g4GgwvFW06XntwLG2THLBHy+UIAJcVxJvMT8Ibp0vG1I5dyECwaX/3ou0t7RT/TRivyHGXTspAcd250OB+2l5zJz6NnVlR2uysm1SMGQUoBMIaVXsx5UTUj1wZwBFNNZ7eifsfvNj4veIWx4lL5t5C3CxEpmUtErBXrm5Z4qZuoMN8swtP310RzXTc+53OtibnVNP137wEtL6r9oe8wJ63esqWM6975zC+0ecXI4qipcg44KfKTrw5+0nT3b9h9+bs/G7uNx9/roE66Zp1ad7uvtmb/lxTu8m/d/EH/44KzJ07JPPv+t2/iz0f3+Jvnw7OYdh9r+WrHmLOyZ95256+Xva8iai+rvB4ZWuU5cOLtx6h7Xufk9rw80cu4jF/c5Fww9m4h89us9J7ete2GoIvGDWvVg3SYcb/xo19f3zjzcvrf7kaP7zmw59sCeIX557dtnzh569yhv5moOAO6NfRMSnSvbX70/857ntc031Zx86ty6zlmc+/am7JFtU9/yfvn4PGLX2p/bzh/86o8Vn7+ydrd017kff5k+jf10StedF7s2zV29td1/8/GOk9ulec+c4np/e3ra+r7zx/TUJ1v3a/XHvxlevr8BJR80Ud0RAAA=

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: false